name: AWS Deploy S3
on: [push, workflow_dispatch]
jobs:
  deploy-to-s3-leo:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: |
          sudo apt update && sudo apt install --no-install-recommends awscli
          aws s3 sync . s3://deploy-to-s3-leo --delete --acl public-read
          echo "Deploy completed"
