name: AWS Deploy S3
on: [push]
jobs:
  deploy-to-s3-leo:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install --no-install-recommends awscli
      - run: aws s3 sync . s3://deploy-to-s3-leo --delete --acl public-read
      - run: echo "Deploy completed"
